keys:
    - &sops_admin age1f6rjhsz7qj0hhmje6ht0388zexwjnrm3vvl4pmt82hzqdxgau3fsvjmdmu
    - &hearth_host age159xmzrxsawm6n9lwvfay5tjrawpt6nl4uhead87hzzeaye53ag3qdqn4jj
    - &sputnik_host age1c9gdrlnxmtgthp8swcf35u6cd8wljlv3d5mhdswjtr99c9kdcq9q8cc8v8

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *sops_admin
          - *hearth_host
          - *sputnik_host
