# modules/hosts/hermes/hardware.nix
# Hermes ARM server hardware configuration
# Generated by nixos-generate-config -- hardware specific only

{ config, lib, pkgs, ... }:

{
  # Note: not-detected.nix is imported by the host configuration

  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
    fsType = "ext4";
  };

  swapDevices = [ ];
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
